### PR TITLE
PMM-5011 PMM-4663 Add SSL support for MySQL connection

### PR DESCRIPTION
**Pull request by percona-csalguero**
Added support to detect SSL options from `.my.cnf` file.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/mysqld_exporter?pullRequest=57) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/mysqld_exporter?pullRequest=57) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/mysqld_exporter?pullRequest=57) it.</sub>

**Comment by AlekSi** [comment]
On hold until we decide about https://jira.percona.com/browse/PMM-5011.

**Comment by denisok** [comment]
@percona-csalguero is this still on-hold?

**Comment by BupycHuk** [comment]
@denisok yes.

**Pull request closed without merging**
