### PR TITLE
Support for MariaDB 10.5+

### PR DESCRIPTION
**Pull request by michnovka**
Ported from https://github.com/prometheus/mysqld_exporter/commit/662d1a17f7f33b70286ab3a35b6f8a045dad0e7c

### CODE REVIEW

**Comment by denisok** [comment]
we plan to sync with upstream in near future, but it is good to incorporate this fix.

@michnovka do you use PMM with this exporter?

**Comment by michnovka** [comment]
Yes, using pmm2-client from your repo on Centos 7. Would appreciate quick
push to repo so that I can update, as I upgraded to MariaDB 10.6 from 10.4
and its hard to debug issues With InnoDB flushing without this.

Thanks

**Comment by denisok** [comment]
Hi @michnovka ,

next release probably would be rolled at the end of the next month if you use release repos. We will land this asap, but client build would need to wait for other fixes and full QA.

Thanks,
Denys

**Review by tshcherban — APPROVED** [review]

**Review by JiriCtvrtka — APPROVED** [review]

**Review by tshcherban — APPROVED** [review]

**Comment by tshcherban** [comment]
we are pulling changes from prometheus, so this PR is outdated and will be closed soon

**Pull request closed without merging**
