### PR TITLE
PMM-4001 optimize infoSchemaAutoIncrementQuery to start FROM columns …

### PR DESCRIPTION
**Pull request by ColinDKelley**
…then STRAIGHT_JOIN to tables

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/mysqld_exporter?pullRequest=48) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/mysqld_exporter?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/mysqld_exporter?pullRequest=48) it.</sub>

**Comment by ColinDKelley** [comment]
@rnovikovP  How does this look?

**Comment by rnovikovP** [comment]
Thanks for PR @ColinDKelley ! 
I just need additional 👀 on this. 
And I'm doing some experimental build to run additional tests. Let you know when it's done

**Comment by ColinDKelley** [comment]
Hi @rnovikovP do you have any estimate for when you might get the experimental build results?
Anything I can help with?

**Comment by AlekSi** [comment]
Hi @ColinDKelley. We looked into it, and not sure why this change fixes a situation for you. May you please provide `EXPLAIN FROM=JSON` for both old and new queries on your system?

**Comment by ColinDKelley** [comment]
@AlekSi  Yes, I will get that this week and post it here.

**Comment by ColinDKelley** [comment]
Hi @AlekSi,

Here is the `explain` from before:
```
mysql> explain format=json SELECT t.table_schema, t.table_name, column_name, `auto_increment`,
    ->   pow(2, case data_type
    ->     when 'tinyint'   then 7
    ->     when 'smallint'  then 15
    ->     when 'mediumint' then 23
    ->     when 'int'       then 31
    ->     when 'bigint'    then 63
    ->     end+(column_type like '% unsigned'))-1 as max_int
    ->   FROM information_schema.tables t
    ->   JOIN information_schema.columns c
    ->     ON BINARY t.table_schema = c.table_schema AND BINARY t.table_name = c.table_name
    ->   WHERE c.extra = 'auto_increment' AND t.auto_increment IS NOT NULL;
{
  "query_block": {
    "select_id": 1,
    "cost_info": {
      "query_cost": "11.90"
    },
    "nested_loop": [
      {
        "table": {
          "table_name": "t",
          "access_type": "ALL",
          "open_full_table": true,
          "scanned_databases": "all",
          "used_columns": [
            "TABLE_CATALOG",
            "TABLE_SCHEMA",
            "TABLE_NAME",
            "TABLE_TYPE",
            "ENGINE",
            "VERSION",
            "ROW_FORMAT",
            "TABLE_ROWS",
            "AVG_ROW_LENGTH",
            "DATA_LENGTH",
            "MAX_DATA_LENGTH",
            "INDEX_LENGTH",
            "DATA_FREE",
            "AUTO_INCREMENT",
            "CREATE_TIME",
            "UPDATE_TIME",
            "CHECK_TIME",
            "TABLE_COLLATION",
            "CHECKSUM",
            "CREATE_OPTIONS",
            "TABLE_COMMENT"
          ],
          "attached_condition": "(`t`.`AUTO_INCREMENT` is not null)"
        }
      },
      {
        "table": {
          "table_name": "c",
          "access_type": "ALL",
          "open_frm_only": true,
          "scanned_databases": "all",
          "using_join_buffer": "Block Nested Loop",
          "used_columns": [
            "TABLE_CATALOG",
            "TABLE_SCHEMA",
            "TABLE_NAME",
            "COLUMN_NAME",
            "ORDINAL_POSITION",
            "COLUMN_DEFAULT",
            "IS_NULLABLE",
            "DATA_TYPE",
            "CHARACTER_MAXIMUM_LENGTH",
            "CHARACTER_OCTET_LENGTH",
            "NUMERIC_PRECISION",
            "NUMERIC_SCALE",
            "DATETIME_PRECISION",
            "CHARACTER_SET_NAME",
            "COLLATION_NAME",
            "COLUMN_TYPE",
            "COLUMN_KEY",
            "EXTRA",
            "PRIVILEGES",
            "COLUMN_COMMENT",
            "GENERATION_EXPRESSION"
          ],
          "attached_condition": "((`c`.`EXTRA` = 'auto_increment') and (cast(`t`.`TABLE_SCHEMA` as char charset binary) = `c`.`TABLE_SCHEMA`) and (cast(`t`.`TABLE_NAME` as char charset binary) = `c`.`TABLE_NAME`))"
        }
      }
    ]
  }
}
```
And here it is after the change:
```
mysql> explain format=json SELECT t.table_schema, t.table_name, column_name, `auto_increment`,
    ->   pow(2, case data_type
    ->     when 'tinyint'   then 7
    ->     when 'smallint'  then 15
    ->     when 'mediumint' then 23
    ->     when 'int'       then 31
    ->     when 'bigint'    then 63
    ->     end+(column_type like '% unsigned'))-1 as max_int
    ->   FROM information_schema.columns c
    ->   STRAIGHT_JOIN information_schema.tables t
    ->     ON BINARY t.table_schema = c.table_schema AND BINARY t.table_name = c.table_name
    ->   WHERE c.extra = 'auto_increment' AND t.auto_increment IS NOT NULL;
{
  "query_block": {
    "select_id": 1,
    "cost_info": {
      "query_cost": "21106.28"
    },
    "nested_loop": [
      {
        "table": {
          "table_name": "c",
          "access_type": "ALL",
          "open_frm_only": true,
          "scanned_databases": "all",
          "used_columns": [
            "TABLE_CATALOG",
            "TABLE_SCHEMA",
            "TABLE_NAME",
            "COLUMN_NAME",
            "ORDINAL_POSITION",
            "COLUMN_DEFAULT",
            "IS_NULLABLE",
            "DATA_TYPE",
            "CHARACTER_MAXIMUM_LENGTH",
            "CHARACTER_OCTET_LENGTH",
            "NUMERIC_PRECISION",
            "NUMERIC_SCALE",
            "DATETIME_PRECISION",
            "CHARACTER_SET_NAME",
            "COLLATION_NAME",
            "COLUMN_TYPE",
            "COLUMN_KEY",
            "EXTRA",
            "PRIVILEGES",
            "COLUMN_COMMENT",
            "GENERATION_EXPRESSION"
          ],
          "attached_condition": "(`c`.`EXTRA` = 'auto_increment')"
        }
      },
      {
        "table": {
          "table_name": "t",
          "access_type": "ALL",
          "open_full_table": true,
          "scanned_databases": "all",
          "using_join_buffer": "Block Nested Loop",
          "used_columns": [
            "TABLE_CATALOG",
            "TABLE_SCHEMA",
            "TABLE_NAME",
            "TABLE_TYPE",
            "ENGINE",
            "VERSION",
            "ROW_FORMAT",
            "TABLE_ROWS",
            "AVG_ROW_LENGTH",
            "DATA_LENGTH",
            "MAX_DATA_LENGTH",
            "INDEX_LENGTH",
            "DATA_FREE",
            "AUTO_INCREMENT",
            "CREATE_TIME",
            "UPDATE_TIME",
            "CHECK_TIME",
            "TABLE_COLLATION",
            "CHECKSUM",
            "CREATE_OPTIONS",
            "TABLE_COMMENT"
          ],
          "attached_condition": "((`t`.`AUTO_INCREMENT` is not null) and (cast(`t`.`TABLE_SCHEMA` as char charset binary) = `c`.`TABLE_SCHEMA`) and (cast(`t`.`TABLE_NAME` as char charset binary) = `c`.`TABLE_NAME`))"
        }
      }
    ]
  }
}
```
Sorry about the slow response! We used that time to put this code live across all our production databases. We've been running PMM this way for the last month across ~20 MySQL servers with no surprises.

**Comment by ColinDKelley** [comment]
@AlekSi does the `explain` output above look good to you?

**Comment by ColinDKelley** [comment]
@AlekSi Just checking in here to see if the `explain` output looks good?

**Comment by AlekSi** [comment]
Sorry for the delay. We talked and tested that PR internally to understand why `query_cost` is larger after the change, but queries are indeed faster. Looks good, merging.

**Comment by ColinDKelley** [comment]
Thank you, @AlekSi!

**Pull request merged**
